jwt:
    secret: jwtsecretkey
spring:
    datasource:
        password: root
        platform: mysql
        url: jdbc:postgresql://localhost:5432/simswap
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
